# Generated by Django 5.1.2 on 2024-11-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id_reseña', models.PositiveSmallIntegerField(max_length=6, primary_key=True, serialize=False)),
                ('id_producto', models.IntegerField()),
                ('id_cliente', models.IntegerField()),
                ('calificacion', models.IntegerField()),
                ('comentario', models.CharField(max_length=100)),
                ('fecha_reseña', models.DateField()),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
    ]
