# Generated by Django 5.1 on 2024-11-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_empleado', models.PositiveSmallIntegerField(max_length=6, primary_key=True, serialize=False)),
                ('id_producto', models.IntegerField()),
                ('id_cliente', models.IntegerField()),
                ('cantidad_producto', models.IntegerField()),
                ('fecha', models.CharField(max_length=100)),
                ('precio_total', models.IntegerField()),
                ('metodo_pago', models.CharField(max_length=100)),
            ],
        ),
    ]
