# Generated by Django 5.1 on 2024-11-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.PositiveSmallIntegerField(max_length=6, primary_key=True, serialize=False)),
                ('id_ventas', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('sexo', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
            ],
        ),
    ]
