# Generated by Django 5.1 on 2024-11-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.PositiveSmallIntegerField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('correo_electronico', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('productos', models.CharField(max_length=100)),
            ],
        ),
    ]
